### ISSUE TITLE
RowClass with lambda expression

### ISSUE THREAD

**Issue by johanskoldekrans** [EngstromJimmy/Blazm.Components#10]
To be able to set a css class on an entire row. For example if an item has been cancelled and you want that to be clearly visible. Can be a strike-through or colored red etc.

**Comment by EngstromJimmy** [comment]
Here is a demo: https://engstromjimmy.github.io/Blazm.Components/rowcss


`<BlazmGrid RowCss="@(r=>{if(r.TemperatureC==0) return ""; else return r.TemperatureC<0?"negative":"positive";})"`
