### ISSUE TITLE
Case sensitivity of folder names not maintained.

### ISSUE THREAD

**Issue by ssathya** [EngstromJimmy/Blazm.Components#19]
While deploying my application onto a Linux platform and stumbled upon a couple of errors caused by Blazm: should be an easy fix.

**GET [domain]/_content/Blazm.Components/css/styles.min.css net::ERR_ABORTED 404 (Not Found)**
_Renamed  Blazm.Components/css/Styles.min.css to Blazm.Components/css/styles.min.css to resolve this issue._

**GET [domain]/_content/Blazm.Components/scripts/ResizeTable.js net::ERR_ABORTED 404 (Not Found)**
_Renamed /_content/Blazm.Components/Scripts to ]/_content/Blazm.Components/scripts to resolve this issue._

**Comment by EngstromJimmy** [comment]
Ah of course!
Great catch! I'll make sure to fix that during the next update.

**Comment by darraghjones** [comment]
I'm encountering a simliar issue when 'publishing' my app:
```
#11 8.626 /usr/share/dotnet/sdk/6.0.100-preview.6.21355.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(252,5): error MSB3030: Could not copy the file "/root/.nuget/packages/blazm.components/1.0.5/staticwebassets/css/Styles.css" because it was not found. [/source/ServiceRegistryUI.csproj]

#11 8.626 /usr/share/dotnet/sdk/6.0.100-preview.6.21355.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(252,5): error MSB3030: Could not copy the file "/root/.nuget/packages/blazm.components/1.0.5/staticwebassets/css/Styles.min.css" because it was not found. [/source/ServiceRegistryUI.csproj]
```

**Comment by EngstromJimmy** [comment]
Now everything should be correct =)
