### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by eajeaj** [EngstromJimmy/Blazm.Components#27]
Please add a LICENSE file (e.g. MIT) to allow using it. Without it you're not really granting others permission to use it.
Awesome project, and book (Web Development with Blazor), BTW!

**Comment by EngstromJimmy** [comment]
I have added a license now, I will make sure to add it to the NuGet when I release a new version.
Thanks for reminding me =)
Happy to hear you like the book =)
